springdoc:
  swagger-ui:
    path: /api/swagger-ui

pathTemp: D:\Document_Study\MySchool\Nam4\Ky II\DATN_FINAL\PCThanhCong_Server\Temp\

mail:
  username : ${MAIL_USERNAME}
  password : ${MAIL_PASSWORD}
storage:
  location: upload-dir

